using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using Shared.LogicSynchronizer;

namespace Shared.Union
{
    public static class UnionFactory
    {
        private const string NL = "\r\n";

        public static string Build(IUnionDecl unionDecl, string nameSpace, string[] usings, bool mergeSubstructures = true)
        {
            StringBuilder sb = new StringBuilder();

            string tab = NL;

            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Shared.Union;");
            {
                HashSet<string> hash = new HashSet<string>();
                foreach (var i in unionDecl.InterfacesToImplement)
                {
                    if (i.Namespace != "")
                    {
                        hash.Add(i.Namespace);
                    }
                }

                foreach (var str in hash)
                {
                    sb.AppendFormat("using {0};{1}", str, NL);
                }
            }

            if (usings != null)
            {
                foreach (var u in usings)
                {
                    sb.AppendFormat("using {0};{1}", u, NL);
                }
            }

            if (nameSpace != null)
            {
                sb.AppendLine(NL + "namespace " + nameSpace);
                sb.Append("{");
                tab += "    ";
            }

            sb.AppendFormat("{0}//{0}//This code is autogenerated. Do not modify it.{0}//", tab);

            if (mergeSubstructures)
            {
                sb.AppendFormat("{0}[StructLayout(LayoutKind.Explicit)]", tab);
            }
            sb.AppendFormat("{0}public struct {1}", tab, unionDecl.TypeName);
            {
                bool first = true;
                foreach (var i in unionDecl.InterfacesToImplement)
                {
                    sb.Append(first ? ": " : ", ");
                    sb.Append(SynchronizerFactory.FullName(i));
                    first = false;
                }
            }
            sb.AppendFormat("{0}{{", tab);

            string tab2 = tab + "    ";

            WriteFields(sb, unionDecl, mergeSubstructures, tab2);

            {
                sb.AppendLine();
                sb.AppendFormat("{0}public enum {1} : byte", tab2, unionDecl.TypeName + "Type");
                sb.AppendFormat("{0}{{", tab2);
                sb.AppendFormat("{0}    Unknown = 0,", tab2);
                WriteStructTypes(sb, unionDecl, tab2 + "    ");
                sb.AppendFormat("{0}}}{1}", tab2, NL);
            }

            WriteStructTypeGetter(sb, unionDecl, tab2);

            WriteProperties(sb, unionDecl, tab2);

            foreach (var prop in unionDecl.PropertiesToImplement)
            {
                WriteProperty(sb, unionDecl, prop, tab2);
            }

            foreach (var mi in unionDecl.MethodsToImplement)
            {
                WriteMethod(sb, unionDecl, mi, tab2);
            }

            sb.AppendFormat("{0}}}{1}", tab, NL);

            if (nameSpace != null)
            {
                sb.Append("}");
            }

            return sb.ToString();
        }

        private static string MakePublicName(string name)
        {
            if (name.Length > 1)
            {
                return Char.ToUpper(name[1]) + name.Substring(2);
            }
            else
            {
                return "The" + name;
            }
        }

        private static void WriteFields(StringBuilder sb, IUnionDecl unionDecl, bool mergeSubstructures, string tab)
        {
            sb.Append(tab);
            if (mergeSubstructures)
            {
                sb.Append("[FieldOffset(0)] ");
            }
            sb.AppendFormat("private {0} mType;{1}", unionDecl.TypeName + "Type", NL);
            foreach (var el in unionDecl.SubTypes)
            {
                sb.Append(tab);
                if (mergeSubstructures)
                {
                    sb.Append("[FieldOffset(1)] ");
                }
                sb.AppendFormat("private {0} {1};", el.TypeName, el.FieldName);
            }
        }

        private static void WriteStructTypes(StringBuilder sb, IUnionDecl unionDecl, string tab)
        {
            foreach (var el in unionDecl.SubTypes)
            {
                sb.AppendFormat("{0}{1},", tab, MakePublicName(el.FieldName));
            }
        }

        private static void WriteStructTypeGetter(StringBuilder sb, IUnionDecl unionDecl, string tab)
        {
            sb.AppendFormat("{0}public {1} Type" +
                            "{0}{{" +
                            "{0}    get {{ return mType; }}" +
                            "{0}}}{2}", tab, unionDecl.TypeName + "Type", NL);
        }

        private static void WriteProperties(StringBuilder sb, IUnionDecl unionDecl, string tab)
        {
            foreach (var el in unionDecl.SubTypes)
            {
                string typeName = el.TypeName;
                string propName = MakePublicName(el.FieldName);

                sb.AppendFormat("{0}public {1} {2}"
                                + "{0}{{"
                                + "{0}    get"
                                + "{0}    {{"
                                + "{0}        if (mType != {5}.{2})"
                                + "{0}        {{"
                                + "{0}            throw new System.InvalidOperationException(\"Unexpected union type: \" + mType);"
                                + "{0}        }}"
                                + "{0}        return {3};"
                                + "{0}    }}"
                                + "{0}    set"
                                + "{0}    {{"
                                + "{0}        mType = {5}.{2};"
                                + "{0}        {3} = value;"
                                + "{0}    }}"
                                + "{0}}}{4}", tab, typeName, propName, el.FieldName, NL, unionDecl.TypeName + "Type");

            }
        }

        private static string PrintMethodParams(MethodInfo mi, bool writeTypes)
        {
            string res = "";

            var parameters = mi.GetParameters();
            for (int i = 0; i < parameters.Length; ++i)
            {
                var param = parameters[i];
                if (i != 0)
                {
                    res += ", ";
                }

                if (param.IsOut)
                {
                    res += "out ";
                }

                if (param.IsRetval)
                {
                    res += "ret ";
                }

                if (writeTypes)
                {
                    res += param.ParameterType.FullName + " ";
                }

                res += param.Name;
            }
            return res;
        }

        private static void WriteProperty(StringBuilder sb, IUnionDecl unionDecl, PropertyInfo prop, string tab)
        {
            sb.AppendFormat("{0}public {1} {2}", tab, prop.PropertyType.FullName, prop.Name);
            sb.AppendFormat("{0}{{", tab);

            if (prop.CanRead)
            {
                sb.AppendFormat("{0}    get" +
                                "{0}    {{" +
                                "{0}         switch (mType)" +
                                "{0}         {{", tab);

                string tab3 = tab + "    " + "    " + "    ";
                foreach (var el in unionDecl.SubTypes)
                {
                    string privateName = el.FieldName;
                    string publicName = MakePublicName(privateName);

                    sb.AppendFormat("{0}case {4}.{1}:" +
                                    "{0}    return {2}.{3};", tab3, publicName, privateName, prop.Name, unionDecl.TypeName + "Type");
                }

                sb.AppendFormat("{0}        default:" +
                                "{0}            throw new System.InvalidOperationException();" +
                                "{0}        }}" +
                                "{0}    }}", tab);
            }

            if (prop.CanWrite)
            {
                sb.AppendFormat("{0}    set" +
                                "{0}    {{" +
                                "{0}         switch (mType)" +
                                "{0}         {{", tab);

                string tab3 = tab + "    " + "    " + "    ";
                foreach (var el in unionDecl.SubTypes)
                {
                    string privateName = el.FieldName;
                    string publicName = MakePublicName(privateName);

                    sb.AppendFormat("{0}case {4}.{1}:" +
                                    "{0}    {2}.{3} = value;" +
                                    "{0}    break;", tab3, publicName, privateName, prop.Name, unionDecl.TypeName + "Type");
                }

                sb.AppendFormat("{0}        default:" +
                                "{0}            throw new System.InvalidOperationException();" +
                                "{0}        }}" +
                                "{0}    }}", tab);
            }

            sb.AppendFormat("{0}}}", tab);
            sb.Append(NL);
        }

        private static void WriteMethod(StringBuilder sb, IUnionDecl unionDecl, IMethodDeclaration method, string tab)
        {
            MethodInfo mi = method.Method;
            var parameters = mi.GetParameters();

            sb.AppendFormat("{0}public{1} {2} {3}({4}){0}{{", tab, mi.DeclaringType == typeof(Object) ? " override" : "", mi.ReturnType.FullName, mi.Name, PrintMethodParams(mi, true));

            bool hasReturnValue = (mi.ReturnType != typeof(void));

            if (hasReturnValue)
            {
                sb.AppendFormat("{0}    {1} res;", tab, mi.ReturnType.FullName);
            }

            foreach (string line in method.AppendBefore())
            {
                sb.AppendFormat("{0}    {1}", tab, line);
            }

            sb.AppendFormat(
                "{0}    switch (mType)" +
                "{0}    {{", tab);

            string methodCall = mi.Name + "(" + PrintMethodParams(mi, false) + ")";

            string tab2 = tab + "    " + "    ";
            foreach (var el in unionDecl.SubTypes)
            {
                string privateName = el.FieldName;
                string publicName = MakePublicName(privateName);

                sb.AppendFormat("{0}case {5}.{1}:" +
                                "{0}    {2}{3}.{4};" +
                                "{0}    break;", tab2, publicName, hasReturnValue ? "res = " : "", privateName, methodCall, unionDecl.TypeName + "Type");
            }

            sb.AppendFormat(
                "{0}        default:" +
                "{0}            throw new System.InvalidOperationException();" +
                "{0}    }}",
                tab, hasReturnValue ? string.Format("{0}    return res;", tab) : "");

            foreach (string line in method.AppendAfter())
            {
                sb.AppendFormat("{0}    {1}", tab, line);
            }
            if (hasReturnValue)
            {
                sb.AppendFormat("{0}    return res;", tab);
            }
            sb.AppendFormat("{0}}}", tab);
            sb.Append(NL);
        }
    }
}
