

public sealed partial class BalancePowerCoeficientHelper
{
    
    static BalancePowerCoeficientHelper()
    {
        MissionTypeCoeficients entry0 = new MissionTypeCoeficients();
        entry0.MissionType = Shared.Meta.MissionType.BasePVE;
        entry0.BaseHeroPower = 2500;
        entry0.StatMultipliers = new System.Collections.Generic.List<StatCoefMap>();
        StatCoefMap entry0subentry0 = new StatCoefMap();
        entry0subentry0.Stat = MobStat.Health;
        entry0subentry0.BalanceCoef = 0.44f;
        entry0subentry0.BaseValue = 0.5f;
        entry0subentry0.Map = new System.Collections.Generic.List<PowerPair>();
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -1000, Multiplier = 1f });
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -1500, Multiplier = 0.75f });
        entry0subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry0.StatMultipliers.Add(entry0subentry0);
        StatCoefMap entry0subentry1 = new StatCoefMap();
        entry0subentry1.Stat = MobStat.AttackDamage;
        entry0subentry1.BalanceCoef = 0.44f;
        entry0subentry1.BaseValue = 0.5f;
        entry0subentry1.Map = new System.Collections.Generic.List<PowerPair>();
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry0subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry0.StatMultipliers.Add(entry0subentry1);
        StatCoefMap entry0subentry2 = new StatCoefMap();
        entry0subentry2.Stat = MobStat.AbilityPower;
        entry0subentry2.BalanceCoef = 0.44f;
        entry0subentry2.BaseValue = 0.5f;
        entry0subentry2.Map = new System.Collections.Generic.List<PowerPair>();
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry0subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry0.StatMultipliers.Add(entry0subentry2);
        Table.Add(entry0);
        MissionTypeCoeficients entry1 = new MissionTypeCoeficients();
        entry1.MissionType = Shared.Meta.MissionType.AlternativePVE;
        entry1.BaseHeroPower = 2500;
        entry1.StatMultipliers = new System.Collections.Generic.List<StatCoefMap>();
        StatCoefMap entry1subentry0 = new StatCoefMap();
        entry1subentry0.Stat = MobStat.Health;
        entry1subentry0.BalanceCoef = 0.44f;
        entry1subentry0.BaseValue = 0.5f;
        entry1subentry0.Map = new System.Collections.Generic.List<PowerPair>();
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry1subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry1.StatMultipliers.Add(entry1subentry0);
        StatCoefMap entry1subentry1 = new StatCoefMap();
        entry1subentry1.Stat = MobStat.AttackDamage;
        entry1subentry1.BalanceCoef = 0.44f;
        entry1subentry1.BaseValue = 0.5f;
        entry1subentry1.Map = new System.Collections.Generic.List<PowerPair>();
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry1subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry1.StatMultipliers.Add(entry1subentry1);
        StatCoefMap entry1subentry2 = new StatCoefMap();
        entry1subentry2.Stat = MobStat.AbilityPower;
        entry1subentry2.BalanceCoef = 0.44f;
        entry1subentry2.BaseValue = 0.5f;
        entry1subentry2.Map = new System.Collections.Generic.List<PowerPair>();
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry1subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry1.StatMultipliers.Add(entry1subentry2);
        Table.Add(entry1);
        MissionTypeCoeficients entry2 = new MissionTypeCoeficients();
        entry2.MissionType = Shared.Meta.MissionType.DailyPVE;
        entry2.BaseHeroPower = 2500;
        entry2.StatMultipliers = new System.Collections.Generic.List<StatCoefMap>();
        StatCoefMap entry2subentry0 = new StatCoefMap();
        entry2subentry0.Stat = MobStat.Health;
        entry2subentry0.BalanceCoef = 0.44f;
        entry2subentry0.BaseValue = 0.5f;
        entry2subentry0.Map = new System.Collections.Generic.List<PowerPair>();
        entry2subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry2subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry2subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry2subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry2subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -1000, Multiplier = 1f });
        entry2subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -2500, Multiplier = 0.75f });
        entry2.StatMultipliers.Add(entry2subentry0);
        StatCoefMap entry2subentry1 = new StatCoefMap();
        entry2subentry1.Stat = MobStat.AttackDamage;
        entry2subentry1.BalanceCoef = 0.44f;
        entry2subentry1.BaseValue = 0.5f;
        entry2subentry1.Map = new System.Collections.Generic.List<PowerPair>();
        entry2subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry2subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry2subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry2subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry2subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -1000, Multiplier = 1f });
        entry2subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -2500, Multiplier = 0.75f });
        entry2.StatMultipliers.Add(entry2subentry1);
        StatCoefMap entry2subentry2 = new StatCoefMap();
        entry2subentry2.Stat = MobStat.AbilityPower;
        entry2subentry2.BalanceCoef = 0.44f;
        entry2subentry2.BaseValue = 0.5f;
        entry2subentry2.Map = new System.Collections.Generic.List<PowerPair>();
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry2subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry2.StatMultipliers.Add(entry2subentry2);
        Table.Add(entry2);
        MissionTypeCoeficients entry3 = new MissionTypeCoeficients();
        entry3.MissionType = Shared.Meta.MissionType.TowerPVE;
        entry3.BaseHeroPower = 2500;
        entry3.StatMultipliers = new System.Collections.Generic.List<StatCoefMap>();
        StatCoefMap entry3subentry0 = new StatCoefMap();
        entry3subentry0.Stat = MobStat.Health;
        entry3subentry0.BalanceCoef = 0.44f;
        entry3subentry0.BaseValue = 0.5f;
        entry3subentry0.Map = new System.Collections.Generic.List<PowerPair>();
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 7f });
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 5f });
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 3f });
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 2f });
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry3subentry0.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry3.StatMultipliers.Add(entry3subentry0);
        StatCoefMap entry3subentry1 = new StatCoefMap();
        entry3subentry1.Stat = MobStat.AttackDamage;
        entry3subentry1.BalanceCoef = 0.44f;
        entry3subentry1.BaseValue = 0.5f;
        entry3subentry1.Map = new System.Collections.Generic.List<PowerPair>();
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 8f });
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 6f });
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 4f });
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 3f });
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry3subentry1.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry3.StatMultipliers.Add(entry3subentry1);
        StatCoefMap entry3subentry2 = new StatCoefMap();
        entry3subentry2.Stat = MobStat.AbilityPower;
        entry3subentry2.BalanceCoef = 0.44f;
        entry3subentry2.BaseValue = 0.5f;
        entry3subentry2.Map = new System.Collections.Generic.List<PowerPair>();
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 1200, Multiplier = 5f });
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 500, Multiplier = 3.5f });
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 200, Multiplier = 2f });
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = 0, Multiplier = 1.5f });
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -500, Multiplier = 1f });
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -1200, Multiplier = 0.75f });
        entry3subentry2.Map.Add(new PowerPair() { MissionPowerAhead = -2400, Multiplier = 0.66f });
        entry3.StatMultipliers.Add(entry3subentry2);
        Table.Add(entry3);
        MissionTypeCoeficients entry4 = new MissionTypeCoeficients();
        entry4.MissionType = Shared.Meta.MissionType.AsyncPVP;
        entry4.BaseHeroPower = 2500;
        entry4.StatMultipliers = new System.Collections.Generic.List<StatCoefMap>();
        StatCoefMap entry4subentry0 = new StatCoefMap();
        entry4subentry0.Stat = MobStat.Health;
        entry4subentry0.BalanceCoef = 0.44f;
        entry4subentry0.BaseValue = 1f;
        entry4subentry0.Map = new System.Collections.Generic.List<PowerPair>();
        entry4.StatMultipliers.Add(entry4subentry0);
        StatCoefMap entry4subentry1 = new StatCoefMap();
        entry4subentry1.Stat = MobStat.AttackDamage;
        entry4subentry1.BalanceCoef = 0.44f;
        entry4subentry1.BaseValue = 1f;
        entry4subentry1.Map = new System.Collections.Generic.List<PowerPair>();
        entry4.StatMultipliers.Add(entry4subentry1);
        StatCoefMap entry4subentry2 = new StatCoefMap();
        entry4subentry2.Stat = MobStat.AbilityPower;
        entry4subentry2.BalanceCoef = 0.44f;
        entry4subentry2.BaseValue = 1f;
        entry4subentry2.Map = new System.Collections.Generic.List<PowerPair>();
        entry4.StatMultipliers.Add(entry4subentry2);
        Table.Add(entry4);
        MissionTypeCoeficients entry5 = new MissionTypeCoeficients();
        entry5.MissionType = Shared.Meta.MissionType.SyncPVE;
        entry5.BaseHeroPower = 3250;
        entry5.StatMultipliers = new System.Collections.Generic.List<StatCoefMap>();
        StatCoefMap entry5subentry0 = new StatCoefMap();
        entry5subentry0.Stat = MobStat.Health;
        entry5subentry0.BalanceCoef = 0.44f;
        entry5subentry0.BaseValue = 1f;
        entry5subentry0.Map = new System.Collections.Generic.List<PowerPair>();
        entry5.StatMultipliers.Add(entry5subentry0);
        StatCoefMap entry5subentry1 = new StatCoefMap();
        entry5subentry1.Stat = MobStat.AttackDamage;
        entry5subentry1.BalanceCoef = 0.44f;
        entry5subentry1.BaseValue = 1f;
        entry5subentry1.Map = new System.Collections.Generic.List<PowerPair>();
        entry5.StatMultipliers.Add(entry5subentry1);
        StatCoefMap entry5subentry2 = new StatCoefMap();
        entry5subentry2.Stat = MobStat.AbilityPower;
        entry5subentry2.BalanceCoef = 0.44f;
        entry5subentry2.BaseValue = 1f;
        entry5subentry2.Map = new System.Collections.Generic.List<PowerPair>();
        entry5.StatMultipliers.Add(entry5subentry2);
        Table.Add(entry5);
    }
}
