<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Pontifex</RootNamespace>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Abstractions\Pontifex.Transports\Pontifex.Transports.csproj" />
    </ItemGroup>

</Project>
