namespace MetaGame
{
    public enum Error : byte
    {
        Success = 0,// No error
        PlayerNotFound,
        BadRequest,
        NotFound,
        FeatureDisabled,
        AccessDenied,
        HeroBusy,
        PlayerBadState,
        AcceptTeamTimeout,
        BattleCreateTimeout,
        PlayerAlreadyAcceptMatch,
        PlayerAlreadyWaitMakeTeam,
        PlayerInBattleMode,
        PlayerNotBattle,
        TeamOtherState,
        ConcurrentAccess,
        PlayerAlreadyAcceptHero,
        PlayerAlreadySelectRunes,
        BattleNotFound,
        SessionLocked,
        PlayerDataLocked,
        LockExpired,
        LockNotFound,
        HeroNotFound,
        PlayerBaned,
        FriendAlreadyPresent,
        FriendListFull,
        TargetFriendListFull,
        FriendInviteYourself,
        FriendInviteNotFound,
        FriendOtherStatus,
        FriendNotFound,
        FriendOffline,
        FriendGroupNotFound,
        FriendGroupLeaveFail,
        FriendGroupDissolveFail,
        FriendGroupRejectFail,
        FriendGroupInviteFail,
        FriendGroupDropFail,
        FriendGroupAlreadyInGroup,
        FriendGroupConfirmFail,
        FriendGroupFull,
        FriendGroupBadSize,
        RuneSetNotFound,
        RunesNotValidated,
        AlreadyPurchased,
        NotEnoughResources,
        NotEnoughPowder,
        PriceNotFound,
        ProductEmpty,
        ProductNotFound,
        PlayerNameBusy,
        PlayerNameIncorrect,
        PlayerAlreadyRename,
        InvalidBattleResults,
        QuestNotFound,
        SlotNotFound,
        BasketNotFound,
        AlreadyRegistered,
        AcceptedHeroNotFound,
        IncorrectHero,
        SelectedHeroNotFound,
        PlayerLevelLess,
        PromoCodeActivationsEnded,
        PromoCodeInvalidTime,
        PromoCodeAlreadyActivated,
        PromoCodeInvalid,
        NoNewContent,
        InvalidPlatform,
        HeroSkinNotFound,
        HeroSkinNotActive,
        HeroSkinNotExists,
        BattleResultsNotFound,
        OfferNotFound,
        PlayerAvatarNotFound,
        CommandNotAvailable,
        SparkResearchError,
        SparkError,
        SparkLocked,
        NotEnoughHeroes,
        NotEnoughLevel,
        VeryFewBattles,
        BadBattleScriptType,

        EquipItemNotFound,
        EquipItemUpgradePriceNotFound,
        EquipItemNotEnoughComponents,
        EquipItemMaxLevelAchived,

        UnknownGeoNode,
        UnknownAutomaticGeoNode,
        UnknownChosenGeoNode,

        InventoryItemNotForSale,

        InventoryItemNotFound,
        InventoryFull,

        MissionNotFound,

        InAppPurchaseValidatingError,
        PushUserIdNotFound,

        Maintenance,

        AchievementStageNotComplete,
        AchievementIsInactive,

        HttpResponseTimeout,

        UnknownLootTable,
        MetaBot,

        LeagueNotFound,
        SeasonNotFound,
        ReportLimit,
        ReportTimeExpired,
        NotEnoughKarma,
        MailFriendGiftLimit,

        BattleItemsBuildIdNotFound,

        BattleItemsBuildNameIncorrect,
        LimitExceeded,
        OfferExpired,

        Undefined = 0xFF
    }
}
