<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Pontifex</RootNamespace>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Actuarius.Memory" Version="0.1.3-dev.0" />
      <PackageReference Include="Scriba" Version="0.2.1-dev.0" />
      <PackageReference Include="Scriba.JsonFactory" Version="0.2.1-dev.0" />
      <PackageReference Include="System.Text.Json" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Converters\NoAck.Raw.Reliable\NoAck.Raw.Unreliable\" />
      <Folder Include="Converters\NoAck.Raw.Unreliable\NoAck.Raw.Reliable\" />
      <Folder Include="Transports\Ack\RR\" />
    </ItemGroup>

</Project>
