using System.Runtime.InteropServices;
using Shared.Union;
using Geom2d;
using Serializer.BinarySerializer;

namespace Geom2d
{
    //
    //This code is autogenerated. Do not modify it.
    //
    public struct Shape: Geom2d.IShape, Serializer.BinarySerializer.IDataStruct
    {
        public static readonly Shape None = new Shape();

        private ShapeType mType;

        private CircleShape mCircle;
        private AxisAlignedRectShape mAxisAlignedRect;

        public enum ShapeType : byte
        {
            Unknown = 0,
            Circle,
            AxisAlignedRect,
        }

        public ShapeType Type
        {
            get { return mType; }
        }

        public CircleShape Circle
        {
            get
            {
                if (mType != ShapeType.Circle)
                {
                    throw new System.InvalidOperationException("Unexpected union type: " + mType);
                }
                return mCircle;
            }
            set
            {
                mType = ShapeType.Circle;
                mCircle = value;
            }
        }

        public AxisAlignedRectShape AxisAlignedRect
        {
            get
            {
                if (mType != ShapeType.AxisAlignedRect)
                {
                    throw new System.InvalidOperationException("Unexpected union type: " + mType);
                }
                return mAxisAlignedRect;
            }
            set
            {
                mType = ShapeType.AxisAlignedRect;
                mAxisAlignedRect = value;
            }
        }

        public Geom2d.Vector Center
        {
            get
            {
                 switch (mType)
                 {
                    case ShapeType.Circle:
                        return mCircle.Center;
                    case ShapeType.AxisAlignedRect:
                        return mAxisAlignedRect.Center;
                default:
                    throw new System.InvalidOperationException();
                }
            }
        }

        public System.Single CircumcircleRadius
        {
            get
            {
                 switch (mType)
                 {
                    case ShapeType.Circle:
                        return mCircle.CircumcircleRadius;
                    case ShapeType.AxisAlignedRect:
                        return mAxisAlignedRect.CircumcircleRadius;
                default:
                    throw new System.InvalidOperationException();
                }
            }
        }

        public Geom2d.Circle CircumCircle(Geom2d.Vector selfPosition)
        {
            Geom2d.Circle res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.CircumCircle(selfPosition);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.CircumCircle(selfPosition);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Single Distance(Geom2d.Vector selfPosition, Geom2d.Vector position)
        {
            System.Single res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.Distance(selfPosition, position);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.Distance(selfPosition, position);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Boolean Intersect(Geom2d.Vector selfPosition, Geom2d.Circle c)
        {
            System.Boolean res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.Intersect(selfPosition, c);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.Intersect(selfPosition, c);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Boolean ContainsIn(Geom2d.Vector selfPosition, Geom2d.Circle c)
        {
            System.Boolean res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.ContainsIn(selfPosition, c);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.ContainsIn(selfPosition, c);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Boolean Intersect(Geom2d.Vector selfPosition, Geom2d.CircleSector cs)
        {
            System.Boolean res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.Intersect(selfPosition, cs);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.Intersect(selfPosition, cs);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Boolean Intersect(Geom2d.Vector selfPosition, Geom2d.Quad q)
        {
            System.Boolean res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.Intersect(selfPosition, q);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.Intersect(selfPosition, q);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Boolean ContainsIn(Geom2d.Vector selfPosition, Geom2d.Quad q)
        {
            System.Boolean res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.ContainsIn(selfPosition, q);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.ContainsIn(selfPosition, q);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public System.Boolean Serialize(Serializer.BinarySerializer.IBinarySerializer dst)
        {
            System.Boolean res;
            byte type = (byte)mType;
            dst.Add(ref type);
            mType = (ShapeType)type;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.Serialize(dst);
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.Serialize(dst);
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

        public override System.String ToString()
        {
            System.String res;
            switch (mType)
            {
                case ShapeType.Circle:
                    res = mCircle.ToString();
                    break;
                case ShapeType.AxisAlignedRect:
                    res = mAxisAlignedRect.ToString();
                    break;
                default:
                    throw new System.InvalidOperationException();
            }
            return res;
        }

    }
}